apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      imagePullSecrets:
        - name: myregistrykey
      containers:
        - name: todo-backend
          image: arskale/todo-backend:latest
          imagePullPolicy: Always
          env:
            - name: UVICORN_PORT
              value: "8000"
          ports:
            - containerPort: 8000
