apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-application
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-application
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: todo-application
    spec:
      containers:
        - name: todo-application
          image: APP_IMAGE
          imagePullPolicy: Always
          env:
            - name: UVICORN_PORT
              value: "8080"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: storage-vol
              mountPath: /app/storage
          resources:
            requests:
              memory: "300Mi"
              cpu: "100m"
            limits:
              memory: "300Mi"
              cpu: "100m"
      volumes:
        - name: storage-vol
          persistentVolumeClaim:
            claimName: todo-pv-claim