apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-pv-claim
  namespace: project
spec:
  storageClassName: todo-pv-claim
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi