apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong
  namespace: exercise-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      imagePullSecrets:
        - name: myregistrykey
      containers:
        - name: ping-pong
          image: arskale/ping-pong:latest
          imagePullPolicy: Always
          env:
            - name: UVICORN_PORT
              value: "3030"
          ports:
            - containerPort: 3030
          resources:
            requests:
              memory: "300Mi"
              cpu: "100m"
            limits:
              memory: "300Mi"
              cpu: "100m"
          volumeMounts:
            - name: logs-vol
              mountPath: /app/logs
      volumes:
        - name: logs-vol
          persistentVolumeClaim:
            claimName: logoutput-pv-claim