apiVersion: apps/v1
kind: Deployment
metadata:
  name: logoutput-reader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logoutput-reader
  template:
    metadata:
      labels:
        app: logoutput-reader
    spec:
      containers:
        - name: logoutput-reader
          image: arskale/log-reader:latest
          imagePullPolicy: Always
          env:
            - name: UVICORN_PORT
              value: "3000"
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: logs-vol
              mountPath: /app/logs
        - name: logoutput-writer
          image: arskale/log-writer:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: logs-vol
              mountPath: /app/logs
      volumes:
        - name: logs-vol
          persistentVolumeClaim:
            claimName: logoutput-pv-claim