apiVersion: apps/v1
kind: Deployment
metadata:
  name: logoutput-reader
  namespace: exercise-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logoutput-reader
  template:
    metadata:
      labels:
        app: logoutput-reader
    spec:
      containers:
        - name: logoutput-reader
          image: arskale/log-reader:latest
          imagePullPolicy: Always
          env:
            - name: UVICORN_PORT
              value: "3000"
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: logoutput-reader-config
                  key: MESSAGE
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: logs-vol
              mountPath: /app/logs
            - name: config-vol
              mountPath: /app/config
        - name: logoutput-writer
          image: arskale/log-writer:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "300Mi"
              cpu: "100m"
            limits:
              memory: "300Mi"
              cpu: "100m"
          volumeMounts:
            - name: logs-vol
              mountPath: /app/logs
              subPath: logs
      volumes:
        - name: logs-vol
          persistentVolumeClaim:
            claimName: logoutput-pv-claim
        - name: config-vol
          configMap:
            name: logoutput-reader-config