apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      imagePullSecrets:
        - name: myregistrykey
      containers:
        - name: log-output
          image: arskale/log-output:latest
          imagePullPolicy: Always
          env:
            - name: UVICORN_PORT
              value: "3000"
          ports:
            - containerPort: 3000