apiVersion: v1
kind: PersistentVolume
metadata:
  name: logoutput-pv-claim
spec:
  storageClassName: logoutput-pv-claim
  capacity:
    storage: 1Gi
  volumeMode: Filesystem 
  accessModes:
  - ReadWriteOnce
  local:
    path: /tmp/kube
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k3d-k3s-default-agent-0