apiVersion: v1
kind: Service
metadata:
  name: logoutput-reader-svc
  namespace: exercise-namespace
spec:
  type: ClusterIP
  selector:
    app: logoutput-reader
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 3000