name: Release project app

on:
  push:
    paths:
      - '.github/workflows/main.yaml'
      - 'project*'

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b
  IMAGE: dwk-environments
  SERVICE: dwk-environments
  BRANCH: ${{ github.ref_name }}

jobs:
  build-publish-deploy:
    name: Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GKE_SA_KEY }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - run: gcloud --quiet auth configure-docker

    - name: Get GKE credentials
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: '${{ env.GKE_CLUSTER }}'
        project_id: '${{ env.PROJECT_ID }}'
        location: '${{ env.GKE_ZONE }}'

    - name: Build Backend Image
      run: docker build -t "gcr.io/$PROJECT_ID/todo-backend:${{ github.sha }}" ./project/backend

    - name: Build Frontend Image
      run: docker build -t "gcr.io/$PROJECT_ID/todo-app:${{ github.sha }}" ./project/app
    
    - name: Build Cronjob Image
      run: docker build -t "gcr.io/$PROJECT_ID/cronjob:${{ github.sha }}" ./project/todo_cronjob

    - name: Push Backend Image
      run: docker push "gcr.io/$PROJECT_ID/todo-backend:${{ github.sha }}"

    - name: Push Frontend Image
      run: docker push "gcr.io/$PROJECT_ID/todo-app:${{ github.sha }}"

    - name: Push Cronjob Image
      run: docker push "gcr.io/$PROJECT_ID/cronjob:${{ github.sha }}"

    - name: Set up Kustomize
      uses: imranismail/setup-kustomize@v2.1.0

    - name: Decrypt secrets with SOPS
      env:
        SOPS_AGE_KEY_FILE_CONTENT: ${{ secrets.SOPS_SECRET }}
      run: |
        echo "$SOPS_AGE_KEY_FILE_CONTENT" > key.txt
        export SOPS_AGE_KEY_FILE=$(pwd)/key.txt
        sops --decrypt project/backend/manifests/secret.enc.yaml | kubectl apply -f -
        rm -f key.txt

    - name: Deploy to GKE
      run: |-
        kubectl create namespace project
        kustomize edit set image BACKEND_IMAGE=gcr.io/$PROJECT_ID/todo-backend:${{ github.sha }}
        kustomize edit set image APP_IMAGE=gcr.io/$PROJECT_ID/todo-app:${{ github.sha }}
        kustomize edit set image CRONJOB=gcr.io/$PROJECT_ID/cronjob:${{ github.sha }}

        kustomize build . | kubectl apply -f -
        kubectl rollout status deployment/todo-backend
        kubectl rollout status deployment/todo-application
        kubectl get services -o wide
